name: qml
channels:
  - conda-forge
  - microsoft
  - defaults
dependencies:
  - qsharp
  - notebook
  - pip
  - pyquil
  - qutip
  - pip:
      - cirq
      - pennylane
      - pennylane-lightning
      - pennylane-sf
      - pennylane-qiskit
      - pennylane-cirq
      - pyzx
      - strawberryfields